create table tb_animal (
  ID_ANIMAL BIGINT generated by default as identity,
  ID_CLIENTE BIGINT,
  data_nascimento DATE,
  especie VARCHAR2(10),
  nome VARCHAR2(100),
  ID_UNIDADE BIGINT,
  primary key (ID_ANIMAL)
);

CREATE TABLE TB_CLIENTE (
  ID BIGINT generated by default as identity,
  NOME_CLIENTE VARCHAR2(100),
  CPF_CLIENTE VARCHAR2(14),
  INADIMPLENTE BOOLEAN,
  ID_UNIDADE BIGINT,
  primary key (ID)
);

CREATE TABLE TB_UNIDADE (
  ID_UNIDADE BIGINT generated by default as identity,
  NOME_UNIDADE VARCHAR2(100),
  ENDERECO_UNIDADE VARCHAR2(300),
  primary key (ID_UNIDADE)
);

CREATE TABLE TB_PRODUTO(
  ID_PRODUTO BIGINT generated by default as identity,
  VALOR_PRODUTO NUMBER(8,2),
  DESCRICAO_PRODUTO VARCHAR2(100),
  ID_ANIMAL BIGINT,
  primary key (ID_PRODUTO)
);

alter table TB_PRODUTO add constraint fk_produto_animal
foreign key (ID_ANIMAL) references tb_animal;

alter table tb_animal add constraint FK_ANIMAL_UNIDADE
foreign key (id_unidade) references TB_UNIDADE;

ALTER TABLE TB_CLIENTE ADD CONSTRAINT FK_CLIENTE_UNIDADE
FOREIGN  KEY (ID_UNIDADE) references TB_UNIDADE;